add shed-kubectl

diff --git a/src/DEBIAN/postinst b/src/DEBIAN/postinst
--- a/src/DEBIAN/postinst
+++ b/src/DEBIAN/postinst
@@ -4,6 +4,10 @@ command -v yq >/dev/null
 if [[ $? -eq 1 ]]; then
   echo "[1;31mError: yq not found![0m please install at [1;31mhttps://github.com/mikefarah/yq[0m." >&2
 fi
+command -v kubectl >/dev/null
+if [[ $? -eq 1 ]]; then
+  echo "[1;31mError: kubectl not found![0m please install at [1;31mhttps://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[0m." >&2
+fi
 
 cat <<___EOF___
 
