standardize name for Shed and KubeConfig

diff --git a/src/lib/init.d/shed-init/50-shed-kubeconfig-use b/src/lib/init.d/shed-init/50-shed-kubeconfig-use
--- a/src/lib/init.d/shed-init/50-shed-kubeconfig-use
+++ b/src/lib/init.d/shed-init/50-shed-kubeconfig-use
@@ -16,14 +16,14 @@ shed-kubeconfig-use() {
         [[ $KUBECONFIG_NUMBER != '2' ]] &&
         [[ $KUBECONFIG_NUMBER != '3' ]] &&
         [[ $KUBECONFIG_NUMBER != '4' ]]; then
-        echo "Invalid Shed Config Number. (found: ${KUBECONFIG_NUMBER})."
+        echo "Invalid KubeConfig Number. (found: ${KUBECONFIG_NUMBER})."
         echo
         echo "  kubeconfig-number: 0|1|2|3|4"
         return
     fi
 
     if [[ -z $(shed-value ".kubeconfig[$KUBECONFIG_NUMBER].context") ]]; then
-        echo "Kube config number [$KUBECONFIG_NUMBER] is not setup." >&2
+        echo "KubeConfig Number [$KUBECONFIG_NUMBER] is not setup." >&2
         return
     fi
 
